In [1]:
#This problem is a 4 by 4 grid, the 5 indicates the pawn, 0 is an empty space in the maze and 7 is an obstacle, the goal is to make the 5 reach the last cell of the maze through q learning

import numpy as np
import random

reward = np.array([[-1,1,-1,1], [-1,1,-1,-1], [-1,1,-1,-1], [-1,-1,-1,1], [-1,-1,-1,1], [-1,-1,1,-1], [-1,-1,-1,-1],
 [-1,-1,-1,1], [-1,-1,-1,1], [-1,-1,-1,-1], [-1,-1,-1,1], [-1,-1,-1,1], [-1,1,-1,-1], [-1,1,-1,-1], [-1,1,-1,-1], [0,0,0,0]])  #Up == 0, Left = 1, Right = 2, Down = 3
l = 0.01
y = 0.6
state = 0
count = 0
Q = np.zeros((16,4))
grid = np.array([[5,0,0,0], [0,0,7,0], [0,7,0,0], [0,0,0,0]])


def swap(arr, a, b, c, d):
  arr[a][b], arr[c][d] = arr[c][d], arr[a][b]
  index1, index2 = np.where(arr == 5)
  index1 = index1[0]
  index2 = index2[0]
  return arr, index1, index2

def get_index(state):
  if state == 0:
    return 0, 0
  elif state == 1:
    return 0, 1
  elif state == 2:
    return 0, 2
  elif state == 3:
    return 0, 3
  elif state == 4:
    return 1, 0
  elif state == 5:
    return 1, 1
  elif state == 6:
    return 1, 2
  elif state == 7:
    return 1, 3
  elif state == 8:
    return 2, 0
  elif state == 9:
    return 2, 1
  elif state == 10:
    return 2, 2
  elif state == 11:
    return 2, 3
  elif state == 12:
    return 3, 0
  elif state == 13:
    return 3, 1
  elif state == 14:
    return 3, 2
  elif state == 15:
    return 3, 3

def get_next_state(state, action):
  if((state >= 0 and state <= 3) and action == 0):
    return state

  if((state == 0 or state == 4 or state == 8 or state == 12) and action == 2):
    return state

  if((state == 3 or state == 7 or state == 11 or state == 15) and action == 1):
    return state

  if((state >= 12 and state <= 15) and action == 3):
    return state

  else:
    if action == 0:
      return state - 4
    elif action == 1:
      return state + 1
    elif action == 2:
      return state - 1
    elif action == 3:
      return state + 4



for i in range(2000):
  state = np.random.randint(0,15)
  while state != 15:
    action = np.argmax(Q[state])
    next_state = get_next_state(state, action)
    print("Action is: ", action)
    Q[state][action] = Q[state][action] + l*(reward[state][action] + y*np.max(Q[next_state, :]) - Q[state, action])
    state = next_state
  print(Q)

#Test
state = 0
print("The grid: \n", grid)
while state != 15:
  a, b = np.where(grid == 5)
  a = a[0]
  b = b[0]
  action = np.argmax(Q[state])
  next_state = get_next_state(state, action)
  x, z = get_index(next_state)
  grid, a, b = swap(grid, a, b, x, z)
  state = next_state
  print("The grid: \n", grid)


Streaming output truncated to the last 5000 lines.
 [-0.00994     1.93439975  0.          0.        ]
 [-0.01        1.59698199  0.          0.        ]
 [-0.01        0.9999195   0.          0.        ]
 [ 0.          0.          0.          0.        ]]
Action is:  3
Action is:  3
Action is:  3
[[-0.01        1.03910175  0.          0.        ]
 [-0.01        1.78404004  0.          0.        ]
 [-0.01        2.06552179  0.          0.        ]
 [-0.01       -0.01       -0.01        1.93451196]
 [-0.01       -0.00994    -0.01        1.77142236]
 [-0.00993928 -0.01        1.16111046  0.        ]
 [ 0.01448136 -0.07242666 -0.0726945  -0.07466374]
 [-0.01       -0.01       -0.01        1.59612376]
 [-0.01       -0.01       -0.01        2.06409674]
 [-0.07255863 -0.07302024  0.02063836 -0.07062757]
 [-0.01       -0.00976358 -0.01        1.1921932 ]
 [-0.01       -0.01       -0.01        0.9997115 ]
 [-0.00994     1.93439975  0.          0.        ]
 [-0.01        1.59698199  0.          